
# Copyright (C) Igor Sysoev
# Copyright (C) Nginx, Inc.


all:
	cd $(OPENSSL)

	perl Configure VC-WIN64A no-shared --prefix=openssl $(OPENSSL_OPT)

	ms\do_win64a

	$(MAKE) -f ms\nt.mak
	$(MAKE) -f ms\nt.mak install
